/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface StelfiSwapInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "FEE_BPS"
      | "RATE_PRECISION"
      | "accumulatedFees"
      | "addPair"
      | "deactivatePair"
      | "getAmountOut"
      | "getLiquidity"
      | "getRate"
      | "getSupportedTokens"
      | "isSupported"
      | "owner"
      | "pairs"
      | "registerToken"
      | "renounceOwnership"
      | "supportedTokens"
      | "swap"
      | "tokenSymbols"
      | "transferOwnership"
      | "updateRate"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeesWithdrawn"
      | "OwnershipTransferred"
      | "PairAdded"
      | "PairDeactivated"
      | "PairUpdated"
      | "Swapped"
      | "TokenRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "FEE_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "RATE_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accumulatedFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addPair",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivatePair",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountOut",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRate",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isSupported",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pairs",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerToken",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenSymbols",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRate",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FEE_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "RATE_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivatePair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pairs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenSymbols",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PairAddedEvent {
  export type InputTuple = [
    fromToken: AddressLike,
    toToken: AddressLike,
    rate: BigNumberish
  ];
  export type OutputTuple = [fromToken: string, toToken: string, rate: bigint];
  export interface OutputObject {
    fromToken: string;
    toToken: string;
    rate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PairDeactivatedEvent {
  export type InputTuple = [fromToken: AddressLike, toToken: AddressLike];
  export type OutputTuple = [fromToken: string, toToken: string];
  export interface OutputObject {
    fromToken: string;
    toToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PairUpdatedEvent {
  export type InputTuple = [
    fromToken: AddressLike,
    toToken: AddressLike,
    newRate: BigNumberish
  ];
  export type OutputTuple = [
    fromToken: string,
    toToken: string,
    newRate: bigint
  ];
  export interface OutputObject {
    fromToken: string;
    toToken: string;
    newRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwappedEvent {
  export type InputTuple = [
    user: AddressLike,
    fromToken: AddressLike,
    toToken: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    fromToken: string,
    toToken: string,
    amountIn: bigint,
    amountOut: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    user: string;
    fromToken: string;
    toToken: string;
    amountIn: bigint;
    amountOut: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenRegisteredEvent {
  export type InputTuple = [token: AddressLike, symbol: string];
  export type OutputTuple = [token: string, symbol: string];
  export interface OutputObject {
    token: string;
    symbol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StelfiSwap extends BaseContract {
  connect(runner?: ContractRunner | null): StelfiSwap;
  waitForDeployment(): Promise<this>;

  interface: StelfiSwapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  RATE_PRECISION: TypedContractMethod<[], [bigint], "view">;

  accumulatedFees: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  addPair: TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, rate: BigNumberish],
    [void],
    "nonpayable"
  >;

  deactivatePair: TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike],
    [void],
    "nonpayable"
  >;

  getAmountOut: TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, amountIn: BigNumberish],
    [[bigint, bigint] & { amountOut: bigint; fee: bigint }],
    "view"
  >;

  getLiquidity: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  getRate: TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike],
    [[bigint, boolean] & { rate: bigint; active: boolean }],
    "view"
  >;

  getSupportedTokens: TypedContractMethod<[], [string[]], "view">;

  isSupported: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pairs: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [[bigint, boolean] & { rate: bigint; active: boolean }],
    "view"
  >;

  registerToken: TypedContractMethod<
    [token: AddressLike, symbol: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  supportedTokens: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  swap: TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, amountIn: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  tokenSymbols: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateRate: TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, newRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RATE_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accumulatedFees"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "addPair"
  ): TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, rate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivatePair"
  ): TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAmountOut"
  ): TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, amountIn: BigNumberish],
    [[bigint, bigint] & { amountOut: bigint; fee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLiquidity"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRate"
  ): TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike],
    [[bigint, boolean] & { rate: bigint; active: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSupportedTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isSupported"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pairs"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [[bigint, boolean] & { rate: bigint; active: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerToken"
  ): TypedContractMethod<
    [token: AddressLike, symbol: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "swap"
  ): TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, amountIn: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokenSymbols"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRate"
  ): TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, newRate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PairAdded"
  ): TypedContractEvent<
    PairAddedEvent.InputTuple,
    PairAddedEvent.OutputTuple,
    PairAddedEvent.OutputObject
  >;
  getEvent(
    key: "PairDeactivated"
  ): TypedContractEvent<
    PairDeactivatedEvent.InputTuple,
    PairDeactivatedEvent.OutputTuple,
    PairDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "PairUpdated"
  ): TypedContractEvent<
    PairUpdatedEvent.InputTuple,
    PairUpdatedEvent.OutputTuple,
    PairUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Swapped"
  ): TypedContractEvent<
    SwappedEvent.InputTuple,
    SwappedEvent.OutputTuple,
    SwappedEvent.OutputObject
  >;
  getEvent(
    key: "TokenRegistered"
  ): TypedContractEvent<
    TokenRegisteredEvent.InputTuple,
    TokenRegisteredEvent.OutputTuple,
    TokenRegisteredEvent.OutputObject
  >;

  filters: {
    "FeesWithdrawn(address,uint256)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PairAdded(address,address,uint256)": TypedContractEvent<
      PairAddedEvent.InputTuple,
      PairAddedEvent.OutputTuple,
      PairAddedEvent.OutputObject
    >;
    PairAdded: TypedContractEvent<
      PairAddedEvent.InputTuple,
      PairAddedEvent.OutputTuple,
      PairAddedEvent.OutputObject
    >;

    "PairDeactivated(address,address)": TypedContractEvent<
      PairDeactivatedEvent.InputTuple,
      PairDeactivatedEvent.OutputTuple,
      PairDeactivatedEvent.OutputObject
    >;
    PairDeactivated: TypedContractEvent<
      PairDeactivatedEvent.InputTuple,
      PairDeactivatedEvent.OutputTuple,
      PairDeactivatedEvent.OutputObject
    >;

    "PairUpdated(address,address,uint256)": TypedContractEvent<
      PairUpdatedEvent.InputTuple,
      PairUpdatedEvent.OutputTuple,
      PairUpdatedEvent.OutputObject
    >;
    PairUpdated: TypedContractEvent<
      PairUpdatedEvent.InputTuple,
      PairUpdatedEvent.OutputTuple,
      PairUpdatedEvent.OutputObject
    >;

    "Swapped(address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      SwappedEvent.InputTuple,
      SwappedEvent.OutputTuple,
      SwappedEvent.OutputObject
    >;
    Swapped: TypedContractEvent<
      SwappedEvent.InputTuple,
      SwappedEvent.OutputTuple,
      SwappedEvent.OutputObject
    >;

    "TokenRegistered(address,string)": TypedContractEvent<
      TokenRegisteredEvent.InputTuple,
      TokenRegisteredEvent.OutputTuple,
      TokenRegisteredEvent.OutputObject
    >;
    TokenRegistered: TypedContractEvent<
      TokenRegisteredEvent.InputTuple,
      TokenRegisteredEvent.OutputTuple,
      TokenRegisteredEvent.OutputObject
    >;
  };
}
